# Generated by Django 4.2.28 on 2026-02-24 09:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aisle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.SlugField()),
                ('name', models.CharField(max_length=100)),
                ('translation_key', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('reference', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'Counties',
            },
        ),
        migrations.CreateModel(
            name='CountyArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('reference', models.SlugField()),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='properties.county')),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('property_type', models.CharField(choices=[('apartment', 'Apartment'), ('house', 'House'), ('terraced-house', 'Terraced House'), ('semi-detached', 'Semi-Detached'), ('detached', 'Detached'), ('bungalow', 'Bungalow'), ('studio', 'Studio'), ('duplex', 'Duplex'), ('townhouse', 'Townhouse')], default='apartment', max_length=50)),
                ('bedroom_count', models.PositiveSmallIntegerField(default=0)),
                ('bathroom_count', models.PositiveSmallIntegerField(default=0)),
                ('price_currency', models.CharField(default='EUR', max_length=5)),
                ('price_symbol', models.CharField(default='€', max_length=5)),
                ('price_min_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_price_on_application', models.BooleanField(default=False)),
                ('rental_period', models.CharField(choices=[('Monthly', 'Monthly'), ('Weekly', 'Weekly'), ('Daily', 'Daily')], default='Monthly', max_length=20)),
                ('ber', models.CharField(blank=True, choices=[('A1', 'A1'), ('A2', 'A2'), ('A3', 'A3'), ('B1', 'B1'), ('B2', 'B2'), ('B3', 'B3'), ('C1', 'C1'), ('C2', 'C2'), ('C3', 'C3'), ('D1', 'D1'), ('D2', 'D2'), ('E1', 'E1'), ('E2', 'E2'), ('F', 'F'), ('G', 'G'), ('Exempt', 'Exempt')], max_length=10)),
                ('ber_number', models.CharField(blank=True, max_length=50)),
                ('property_size_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ad_address', models.CharField(max_length=500)),
                ('eir_code', models.CharField(blank=True, max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('available_from', models.DateField(blank=True, null=True)),
                ('ad_link', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aisle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='properties.aisle')),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='properties.county')),
                ('county_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='properties.countyarea')),
            ],
            options={
                'verbose_name_plural': 'Properties',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertySizeUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('reference', models.SlugField(unique=True)),
                ('symbol', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('translation_key', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SellerType',
            fields=[
                ('id', models.IntegerField(choices=[(1, 'Private'), (2, 'Agent/Broker')], primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('profile_id', models.SlugField(unique=True)),
                ('picture', models.URLField(blank=True)),
                ('tagline', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('phone_code', models.CharField(default='+353', max_length=10)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_disabled', models.BooleanField(default=False)),
                ('has_business_profile', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seller_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='properties.sellertype')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('is_cover', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.property')),
            ],
            options={
                'ordering': ['-is_cover', 'order'],
            },
        ),
        migrations.AddField(
            model_name='property',
            name='property_size_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.propertysizeunit'),
        ),
        migrations.AddField(
            model_name='property',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='properties.section'),
        ),
        migrations.AddField(
            model_name='property',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='properties.seller'),
        ),
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(max_length=200)),
                ('sender_email', models.EmailField(max_length=254)),
                ('sender_phone', models.CharField(blank=True, max_length=20)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enquiries', to='properties.property')),
            ],
            options={
                'verbose_name_plural': 'Enquiries',
            },
        ),
        migrations.AddField(
            model_name='aisle',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aisles', to='properties.section'),
        ),
    ]
